/**
 * Guide Page Template
 * 
 * Template for documentation guides with enhanced navigation and styling
 */

import React from 'react'
import { MDXContent } from '../../utils/mdxLoader'
import { PageTemplateProps } from './page'
import '../../styles/templates/guide.css'

const GuideTemplate: React.FC<PageTemplateProps> = ({ content, params, children }) => {
  const { frontmatter } = content
  
  return (
    <div className="guide-page">
      <div className="container">
        <header className="guide-header">
          <div className="breadcrumb">
            <a href="/guides">Guides</a>
            <span className="breadcrumb-separator"> / </span>
            <span>{frontmatter.title}</span>
          </div>
          
          <div className="guide-meta">
            {frontmatter.audience && (
              <div className="guide-audience">
                <span className="meta-label">For:</span>
                <span className="meta-value">{frontmatter.audience}</span>
              </div>
            )}
            {frontmatter.difficulty && (
              <div className="guide-difficulty">
                <span className="meta-label">Level:</span>
                <span className="meta-value">{frontmatter.difficulty}</span>
              </div>
            )}
            {frontmatter.readingTime && (
              <div className="guide-reading-time">
                <span className="meta-label">Reading time:</span>
                <span className="meta-value">{frontmatter.readingTime}</span>
              </div>
            )}
          </div>
          
          <h1>{frontmatter.title}</h1>
          {frontmatter.description && (
            <p className="guide-description">{frontmatter.description}</p>
          )}
        </header>
        
        <div className="guide-content">
          {children}
        </div>
        
        {/* Table of Contents could be added here */}
        {frontmatter.showToc !== false && (
          <nav className="guide-toc" aria-label="Table of contents">
            {/* TOC will be generated by MDX processor or client-side */}
          </nav>
        )}
      </div>
    </div>
  )
}

export default GuideTemplate