# Component Configuration and Metadata
# Defines component examples, tokens, and documentation structure

components:
  button:
    elevate_component: "elvt-button"
    category: "interactive"
    status: "stable"
    version: "1.2.0"
    description: "Interactive button components for user actions"
    
    props:
      - name: "tone"
        type: "string"
        required: true
        options: ["primary", "secondary", "tertiary", "danger"]
        default: "primary"
        description: "Visual style and importance level"
        
      - name: "size" 
        type: "string"
        required: false
        options: ["small", "medium", "large"]
        default: "medium"
        description: "Button size variation"
        
      - name: "disabled"
        type: "boolean"
        required: false
        default: false
        description: "Disables button interaction"

    tokens:
      - name: "--esds-button-background"
        category: "color"
        description: "Button background color"
        
      - name: "--esds-button-text-color"
        category: "color" 
        description: "Button text color"
        
      - name: "--esds-button-border-color"
        category: "color"
        description: "Button border color"
        
      - name: "--esds-button-padding"
        category: "spacing"
        description: "Button internal padding"

    examples:
      - name: "primary"
        title: "Primary Button"
        description: "Main call-to-action button"
        code: '<elvt-button tone="primary">Primary Action</elvt-button>'
        
      - name: "secondary" 
        title: "Secondary Button"
        description: "Secondary action button"
        code: '<elvt-button tone="secondary">Secondary Action</elvt-button>'
        
      - name: "sizes"
        title: "Button Sizes"
        description: "Available size variations"
        code: |
          <elvt-button size="small">Small</elvt-button>
          <elvt-button size="medium">Medium</elvt-button>
          <elvt-button size="large">Large</elvt-button>
        
      - name: "disabled"
        title: "Disabled State"
        description: "Non-interactive button state"
        code: '<elvt-button disabled>Disabled Button</elvt-button>'

  input:
    elevate_component: "elvt-input"
    category: "forms"
    status: "stable"
    version: "1.1.0"
    description: "Text input components for forms"
    
    props:
      - name: "type"
        type: "string"
        required: false
        options: ["text", "email", "password", "number", "search"]
        default: "text"
        description: "Input type and validation"
        
      - name: "placeholder"
        type: "string"
        required: false
        description: "Placeholder text when empty"
        
      - name: "required"
        type: "boolean"
        required: false
        default: false
        description: "Marks field as required"

    examples:
      - name: "basic"
        title: "Basic Input"
        code: '<elvt-input placeholder="Enter text"></elvt-input>'
        
      - name: "email"
        title: "Email Input"
        code: '<elvt-input type="email" placeholder="Enter email"></elvt-input>'
        
      - name: "required"
        title: "Required Field"
        code: '<elvt-input placeholder="Required field" required></elvt-input>'

  card:
    elevate_component: "elvt-card"
    category: "containers"
    status: "stable"
    version: "1.0.0"
    description: "Content containers with consistent styling"
    
    props:
      - name: "elevation"
        type: "string"
        required: false
        options: ["none", "low", "medium", "high"]
        default: "low"
        description: "Visual elevation and shadow depth"

    examples:
      - name: "basic"
        title: "Basic Card"
        code: |
          <elvt-card>
            <h3>Card Title</h3>
            <p>Card content goes here.</p>
          </elvt-card>
          
      - name: "elevated"
        title: "Elevated Card"  
        code: |
          <elvt-card elevation="medium">
            <h3>Elevated Card</h3>
            <p>Card with medium elevation.</p>
          </elvt-card>

  modal:
    elevate_component: "elvt-modal"
    category: "overlays"
    status: "beta"
    version: "0.9.0" 
    description: "Overlay dialogs for focused interactions"
    
    props:
      - name: "open"
        type: "boolean"
        required: true
        description: "Controls modal visibility"
        
      - name: "size"
        type: "string" 
        required: false
        options: ["small", "medium", "large", "full"]
        default: "medium"
        description: "Modal size variation"

    examples:
      - name: "basic"
        title: "Basic Modal"
        code: |
          <elvt-modal open>
            <h2>Modal Title</h2>
            <p>Modal content goes here.</p>
          </elvt-modal>

# Global component configuration
global:
  # Default example container settings
  example_container:
    padding: "var(--esds-spacing-md)"
    background: "var(--esds-color-background-primary)"
    border: "1px solid var(--esds-color-border-light)"
    border_radius: "var(--esds-radius-md)"
    
  # Code block configuration
  code_block:
    theme: "github"
    line_numbers: true
    copy_button: true
    language_detection: true
    
  # Token table display settings
  token_table:
    show_values: true
    show_fallbacks: true
    grouping: "category"
    sort_order: "alphabetical"