# Navigation Configuration for ELEVATE Documentation Site
navigation:
  main:
    - title: "Getting Started"
      sections:
        - title: "Introduction"
          path: "/guides/introduction"
          description: "Welcome to the ELEVATE Design System"
        - title: "Installation"
          path: "/guides/installation"
          description: "How to install and set up ELEVATE components"
        - title: "Contributing"
          path: "/guides/contributing"
          description: "Guidelines for contributing to ELEVATE"
    
    - title: "Design Tokens"
      sections:
        - title: "Colors"
          path: "/tokens/colors"
          description: "Color palette and usage guidelines"
        - title: "Typography"
          path: "/tokens/typography"
          description: "Font families, sizes, and text styles"
        - title: "Spacing"
          path: "/tokens/spacing"
          description: "Spacing scale and layout guidelines"
        - title: "Shadows"
          path: "/tokens/shadows"
          description: "Shadow tokens for depth and elevation"

    - title: "Components"
      sections:
        - title: "Button"
          path: "/components/button"
          component: "elvt-button"
          description: "Interactive button components for user actions"
        - title: "Input"
          path: "/components/input"
          component: "elvt-input"
          description: "Text input components for forms"
        - title: "Card"
          path: "/components/card"
          component: "elvt-card"
          description: "Content containers with consistent styling"
        - title: "Modal"
          path: "/components/modal"
          component: "elvt-modal"
          description: "Overlay dialogs for focused interactions"

    - title: "Patterns"
      sections:
        - title: "Form Layouts"
          path: "/patterns/form-layouts"
          description: "Common form layout patterns and best practices"
        - title: "Navigation"
          path: "/patterns/navigation"
          description: "Navigation patterns and user flow guidelines"
        - title: "Data Display"
          path: "/patterns/data-display"
          description: "Patterns for displaying complex data sets"

# Secondary navigation for additional resources
secondary:
  footer:
    - title: "Resources"
      links:
        - title: "GitHub Repository"
          url: "https://github.com/owrede-inform/elevate-docsite"
          external: true
        - title: "Component Library"
          url: "https://www.npmjs.com/package/@inform-elevate/elevate-core-ui"
          external: true
    
    - title: "Community"
      links:
        - title: "Report Issues"
          url: "https://github.com/owrede-inform/elevate-docsite/issues"
          external: true
        - title: "Discussions"
          url: "https://github.com/owrede-inform/elevate-docsite/discussions"
          external: true

# Mobile navigation configuration
mobile:
  breakpoint: 768
  collapsible_sections: true
  search_enabled: true