# Global Site Configuration
# Core settings and metadata for the ELEVATE Documentation Site

site:
  # Basic site information
  title: "ELEVATE Design System"
  description: "Comprehensive design system documentation for building exceptional user experiences"
  version: "1.0.0"
  base_url: "https://owrede-inform.github.io/elevate-docsite/"
  
  # Site metadata
  metadata:
    author: "INFORM"
    keywords: ["design system", "components", "ELEVATE", "React", "TypeScript"]
    language: "en"
    theme_color: "#0066cc"
    
  # Brand configuration
  brand:
    name: "ELEVATE"
    tagline: "Design System"
    logo:
      light: "/data/images/inform-brand.svg"
      dark: "/data/images/inform-brand-dark.svg"
      height: "1rem"
    colors:
      primary: "#0066cc"
      secondary: "#0090A7"

  # Content configuration
  content:
    # MDX processing settings
    mdx:
      rehype_plugins:
        - "rehype-slug"
        - "rehype-autolink-headings" 
        - "rehype-highlight"
      remark_plugins:
        - "remark-gfm"
      
    # Frontmatter schema validation
    frontmatter:
      required_fields: ["title", "description"]
      optional_fields: ["category", "tags", "status", "version", "elevate_component"]
      
    # Content organization
    structure:
      content_dir: "content"
      config_dir: "config"
      asset_dirs: ["data", "public"]

  # Feature flags
  features:
    # Theme and appearance
    dark_mode: true
    theme_toggle: true
    
    # Navigation
    search: true
    breadcrumbs: true
    table_of_contents: true
    
    # Content features
    code_highlighting: true
    live_examples: true
    token_visualization: true
    
    # Performance
    lazy_loading: true
    service_worker: false
    
  # Build and deployment
  build:
    # Vite configuration overrides
    vite:
      base: "/elevate-docsite/"
      
    # Asset optimization
    assets:
      minify_css: true
      minify_js: true
      optimize_images: true
      
    # Bundle splitting
    chunks:
      vendor: ["react", "react-dom", "react-router-dom"]
      components: ["@inform-elevate/elevate-core-ui"]
      
  # Development settings  
  development:
    hot_reload: true
    error_overlay: true
    source_maps: true
    
  # Analytics and monitoring (optional)
  analytics:
    enabled: false
    provider: null # "google-analytics", "plausible", etc.
    tracking_id: null
    
  # Accessibility settings
  accessibility:
    skip_links: true
    focus_management: true
    aria_live_regions: true
    reduced_motion_support: true
    high_contrast_support: true
    
  # Performance budgets
  performance:
    # Bundle size limits (in KB)
    budgets:
      initial: 500
      total: 2000
      css: 100
      
    # Core Web Vitals targets
    metrics:
      lcp: 2500  # Largest Contentful Paint (ms)
      fid: 100   # First Input Delay (ms) 
      cls: 0.1   # Cumulative Layout Shift
      
  # Deployment configuration
  deployment:
    platform: "github-pages"
    branch: "main"
    build_command: "npm run build"
    publish_dir: "dist"
    
    # Environment-specific settings
    environments:
      production:
        base_url: "https://owrede-inform.github.io/elevate-docsite/"
        minification: true
        
      development:
        base_url: "http://localhost:3000"
        minification: false