# Design Token System Configuration
# Three-tier architecture: ELEVATE Primitive → ELEVATE Alias → ESDS Component

token_system:
  # Define the three-tier token architecture
  layers:
    - name: "ELEVATE Primitive"
      prefix: "--elvt-primitives-"
      description: "Base design tokens from ELEVATE core system"
      source: "@inform-elevate/elevate-core-ui/tokens"
      immutable: true
      
    - name: "ELEVATE Alias"  
      prefix: "--elvt-alias-"
      description: "Semantic tokens that reference primitive tokens"
      inherits: "ELEVATE Primitive"
      immutable: true
      
    - name: "ESDS Primitive"
      prefix: "--esds-primitives-"
      description: "Documentation site specific primitive tokens"
      inherits: "ELEVATE Primitive"
      can_override: true
      
    - name: "ESDS Alias"
      prefix: "--esds-alias-"
      description: "Documentation site semantic tokens"
      inherits: ["ELEVATE Alias", "ESDS Primitive"]
      can_override: true
      
    - name: "ESDS Component"
      prefix: "--esds-"
      description: "Final component-specific tokens for documentation UI"
      inherits: ["ESDS Alias", "ELEVATE Alias", "ESDS Primitive", "ELEVATE Primitive"]
      extensions: true

  # Token categories and their expected structure
  categories:
    color:
      primitive_tokens:
        - "gray-50"
        - "gray-100" 
        - "gray-200"
        - "gray-300"
        - "gray-400"
        - "gray-500"
        - "gray-600"
        - "gray-700"
        - "gray-800"
        - "gray-900"
        - "blue-50"
        - "blue-500"
        - "blue-600"
        - "blue-700"
      alias_tokens:
        - "background-primary"
        - "background-secondary"
        - "text-primary"
        - "text-secondary"
        - "text-accent"
        - "border-light"
        - "border-medium"
        - "surface-hover"
        - "surface-selected"
      component_tokens:
        - "sidebar-background"
        - "header-background"
        - "code-background"
        - "example-border"

    spacing:
      primitive_tokens:
        - "xs"   # 0.25rem
        - "sm"   # 0.5rem  
        - "md"   # 1rem
        - "lg"   # 1.5rem
        - "xl"   # 2rem
        - "2xl"  # 3rem
      alias_tokens:
        - "component"
        - "section"
        - "page"
      component_tokens:
        - "sidebar-padding"
        - "content-padding"
        - "example-padding"

    typography:
      primitive_tokens:
        - "font-size-xs"
        - "font-size-sm" 
        - "font-size-base"
        - "font-size-lg"
        - "font-size-xl"
        - "font-weight-regular"
        - "font-weight-medium"
        - "font-weight-semibold"
        - "line-height-tight"
        - "line-height-normal"
        - "line-height-relaxed"
      alias_tokens:
        - "heading-primary"
        - "heading-secondary"
        - "body-primary"
        - "body-secondary"
      component_tokens:
        - "sidebar-text"
        - "code-text"
        - "example-caption"

# Live Example component token isolation rules
live_example:
  isolation_mode: "elevate_only"
  description: "EsdsLiveExample component uses only ELEVATE tokens"
  allowed_prefixes:
    - "--elvt-primitives-"
    - "--elvt-alias-"
  blocked_prefixes:
    - "--esds-primitives-"
    - "--esds-alias-"
    - "--esds-"
  
  # CSS containment strategy
  containment:
    style: true
    layout: false
    paint: false
    size: false

# Token validation rules
validation:
  required_fallbacks: true
  circular_references: false
  unused_tokens: "warn"
  missing_primitives: "error"